# Generated by Django 3.2 on 2022-09-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=50)),
                ('course', models.CharField(choices=[('1', 'python'), ('2', 'javascript'), ('3', 'django'), ('4', 'sql'), ('5', 'mangodb')], default='1', max_length=20)),
                ('contact', models.IntegerField()),
            ],
        ),
    ]
