# Generated by Django 3.2 on 2022-09-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=30)),
                ('gender', models.CharField(choices=[('1', 'male'), ('2', 'female'), ('3', 'others')], default='1', max_length=20)),
                ('contact', models.PositiveIntegerField()),
            ],
        ),
    ]
