# Generated by Django 3.2 on 2022-09-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student1'),
    ]

    operations = [
        migrations.AddField(
            model_name='student1',
            name='course',
            field=models.CharField(default='nocourse', max_length=20),
            preserve_default=False,
        ),
    ]
