# Generated by Django 3.2 on 2022-09-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_student1_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='student1',
            name='fee',
            field=models.SmallIntegerField(default='200'),
        ),
    ]
