# Generated by Django 3.2 on 2022-09-05 14:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_student1_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='student1',
            name='sesstime',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
