# Generated by Django 3.2 on 2022-09-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_student2'),
    ]

    operations = [
        migrations.AddField(
            model_name='student2',
            name='fee',
            field=models.SmallIntegerField(default='1000'),
        ),
    ]
